### ISSUE TITLE
Design intent of side panel holes?

### ISSUE THREAD

**Issue by cmbuck** [milelo/AirGradientCase#1]
Hi Mike,

Thanks for sharing your design of the AirGradient case, very excited to try out this case.  Question for you: What is the design intent of the holes on one of the side panels right here?  Are these for airflow?

![image](https://user-images.githubusercontent.com/1079028/174697787-39b17250-bd54-473d-a4e6-dfe9c99d140a.png)
![image](https://user-images.githubusercontent.com/1079028/174697851-5e79e880-8cf5-40dd-a659-5e04dfc8c734.png)

Best regards,
Christopher

**Comment by milelo** [comment]
Hi,
  They are for mounting sensors closer to the air flow inside the case like the VOC sensor, the holes are tapped.
Incidentally the VOC sensor, as suggested in the DIY design, doesn't work for me and many people. I haven't got round to trying to debug the issue yet.

Note also the height of the unit could be reduced by about 4mm if you wanted to reduce it. This is mainly parameterised but there may be issues with the air flow slots.

**Comment by cmbuck** [comment]
Oh interesting, I was not aware of the VOC sensor option.  Perhaps that info is new since I last built my unit, or perhaps I missed it the first go-round.  I'll look into that.

Thanks for the tip on the unit height.  I'll try making one as is and revisit this if I can learn the basics of FreeCAD.
